import { StyleSheet } from "react-native";

const mzStyles = StyleSheet.create({
  mzContainer: {
    // position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#F2E7E7",
    display: "flex",
    gap: 4,
    // paddingLeft: 20,
    // paddingRight: 20,
    borderTopRightRadius: 28,
    borderTopLeftRadius: 28,

    overflow: "hidden",
    // zIndex: 50,
  },
  mzBoxOne: {
    display: "flex",
  },
  mzWrapperOne: {
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    // justifyContent: 'center',
    alignItems: "center",
    gap: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 6,
    paddingBottom: 20,
  },
  mzWrapperTwo: {
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    // justifyContent: 'center',
    alignItems: "center",
    gap: 20,
    // paddingLeft: 20,
    // paddingRight: 20,
    paddingTop: 20,
  },
  addValueZone: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    alignSelf: "stretch",
    gap: 12,
    paddingLeft: 20,
    paddingRight: 20,
  },
  addValueZoneTitle: {
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 20,
    color: "#000",
  },
  scValueBox: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    gap: 4,
  },
  scValueTime: {
    display: "flex",
    flexDirection: "row",
    gap: 40,
  },
  scValueTimeTxt: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    color: "#646161",
  },
  scValueTimeTxtActive: {
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    color: "#000",
  },

  lineModSwipe: {
    width: 36,
    height: 4,
    backgroundColor: "#CACACA",
    borderRadius: 4,
  },
  ZoneModHeadBox: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    alignSelf: "stretch",
    gap: 6,
    padding: 0,
  },
  h5Headung: {
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 28,
    color: "#000",
  },
  subTitle: {
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    color: "#646161",
  },
  subTitleAlertDesc:{
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    color: "#3C3A3A",
  },
  ZoneModDescrBox: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    alignSelf: "stretch",
    padding: 12,
    gap: 6,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
  },
  ZnakModIcon: {
    width: 48,
    height: 48,
  },
  ZnakModIconTxt: {
    display: "flex",
    flexShrink: 1,
  },
  ModIconInfo: {
    width: 24,
    height: 24,
  },
  BtnBox: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "stretch",
    paddingTop: 20,
    paddingBottom: 20,
    borderTopColor: "#F6F6F6",
    borderTopWidth: 1,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: "#fff",
  },
  BtnBoxTwoVert:{
    flex: 1,
    gap: 16,
  },
  BtnOk: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 56,
    width: "100%",
    fontSize: 20,
    // backgroundColor: '#E5F64A',
    backgroundColor: "#FEC303",
    borderRadius: 16,
  },
  BtnOkTxt: {
    fontSize: 17,
    fontWeight: "700",
    lineHeight: 20,
    // letterSpacing: -1,
    color: "#2E3032",
  },
  disabledBtn: {
    backgroundColor: '#F0F0F0',
  },
});

export default mzStyles;
